export const CLASSES = {
  warrior: {
    nameKey: "class.warrior",
    attackType: "melee",
    modifiers: {
      hp: 0.3,
      mp: -0.8,
      str: 0.4,
      vit: 0.3,
      armor: 0.4,
      mres: 0.0,
    },
    passives: {},
    skills: [],
  },
  barbarian: {
    nameKey: "class.barbarian",
    attackType: "melee",
    modifiers: {
      hp: 0.4,
      mp: -1.0,
      str: 0.6,
      armor: 0.2,
      mres: -0.2,
      dex: 0.1,
    },
    passives: {},
    skills: [],
  },
  paladin: {
    nameKey: "class.paladin",
    attackType: "melee",
    modifiers: {
      hp: 0.25,
      mp: 0.2,
      str: 0.25,
      vit: 0.25,
      armor: 0.3,
      mres: 0.3,
    },
    passives: {},
    skills: [],
  },
  rogue: {
    nameKey: "class.rogue",
    attackType: "melee",
    modifiers: {
      hp: -0.1,
      mp: -0.5,
      dex: 0.6,
      str: 0.1,
      armor: -0.3,
      critChanceBonus: 0.2,
    },
    passives: {},
    skills: [],
  },
  archer: {
    nameKey: "class.archer",
    attackType: "melee",
    modifiers: {
      hp: -0.05,
      mp: -0.3,
      dex: 0.5,
      str: 0.2,
      armor: -0.2,
      critChanceBonus: 0.1,
    },
    passives: {},
    skills: [],
  },
  mage: {
    nameKey: "class.mage",
    attackType: "magic",
    modifiers: {
      hp: -0.3,
      mp: 0.8,
      int: 0.6,
      armor: -0.6,
      mres: 0.3,
      str: -0.8,
    },
    passives: {},
    skills: ["magicBolt"],
  },
  warlock: {
    nameKey: "class.warlock",
    attackType: "magic",
    modifiers: {
      hp: -0.2,
      mp: 0.6,
      int: 0.5,
      armor: -0.5,
      mres: 0.2,
      magicCritChanceBonus: 0.1,
    },
    passives: {},
    skills: ["magicBolt"],
  },
  necromancer: {
    nameKey: "class.necromancer",
    attackType: "magic",
    modifiers: {
      hp: -0.1,
      mp: 0.5,
      int: 0.45,
      armor: -0.4,
      mres: 0.4,
    },
    passives: {
      lifeStealPct: 0.15,
    },
    skills: ["magicBolt"],
  },
  druid: {
    nameKey: "class.druid",
    attackType: "magic",
    modifiers: {
      hp: 0.1,
      mp: 0.4,
      int: 0.3,
      vit: 0.2,
      armor: -0.1,
      mres: 0.2,
    },
    passives: {},
    skills: ["magicBolt"],
  },
};
