export const SCENES = {
  PRELOAD: "PreloadScene",
  SPLASH: "SplashScene",
  MENU: "MainMenuScene",
  SETTINGS: "SettingsScene",
  CHARACTER_CREATION: "CharacterCreationScene",
  GAME: "GameScene",
};

export const ASSETS = {
  PLAYER: "player",
  ENEMY: "enemy",
  TILESET_MAIN: "tileset",
  TILESET_GRASS: "TX Tileset Grass",
  TILESET_STONE_GROUND: "TX Tileset Stone Ground",
  TILESET_WALL: "TX Tileset Wall",
  TILESET_PROPS: "TX Props",
  TILESET_STRUCT: "TX Struct",
  TILESET_PLANT: "TX Plant",
  TILESET_SHADOW: "TX Shadow",
  TILESET_SHADOW_PLANT: "TX Shadow Plant",
  TILESET_PLAYER: "TX Player",
  MAP_V0: "mapv0",
  MENU: "menu",
  MENU_BG: "menu_bg",
  MENU_NEW: "menu_new",
  MENU_LOAD: "menu_load",
  MENU_SETTINGS: "menu_settings",
  MENU_EXIT: "menu_exit",
  MENU_LOGO: "menu_logo",
  MENU_KNIGHT: "menu_knight",
  CHARACTER_CREATION_BG: "character_creation_bg",
  CHARACTER_CREATION_FOG: "character_creation_fog",
  CHARACTER_CREATION_ASH: "character_creation_ash",
  CHARACTER_CREATION_BACK: "character_creation_back",
  CHARACTER_CREATION_START: "character_creation_start",
  CHARACTER_CREATION_BOX_LEFT: "character_creation_box_left",
  CHARACTER_CREATION_BOX_RIGHT: "character_creation_box_right",
  CHARACTER_CREATION_BOX_BONUS: "character_creation_box_bonus",
  CHARACTER_CREATION_BOX_PREVIEW: "character_creation_box_preview",
  CHARACTER_CREATION_ARROW_LEFT: "character_creation_arrow_left",
  CHARACTER_CREATION_ARROW_RIGHT: "character_creation_arrow_right",
  CHARACTER_CREATION_PREVIEW_ARROW_LEFT: "character_creation_preview_arrow_left",
  CHARACTER_CREATION_PREVIEW_ARROW_RIGHT: "character_creation_preview_arrow_right",
  CHARACTER_CREATION_TITLE: "character_creation_title",
  HUMAN_BASE_FRONT: "human_base_front",
  HUMAN_BASE_PROFILE_LEFT: "human_base_profile_left",
  HUMAN_BASE_PROFILE_RIGHT: "human_base_profile_right",
  HUMAN_BASE_BACK: "human_base_back",
  HUMAN_FEMALE_BASE_FRONT: "human_female_base_front",
  HUMAN_FEMALE_BASE_PROFILE_LEFT: "human_female_base_profile_left",
  HUMAN_FEMALE_BASE_PROFILE_RIGHT: "human_female_base_profile_right",
  HUMAN_FEMALE_BASE_BACK: "human_female_base_back",
  ELF_BASE_FRONT: "elf_base_front",
  ELF_BASE_PROFILE_LEFT: "elf_base_profile_left",
  ELF_BASE_PROFILE_RIGHT: "elf_base_profile_right",
  ELF_BASE_BACK: "elf_base_back",
  ELF_FEMALE_BASE_FRONT: "elf_female_base_front",
  ELF_FEMALE_BASE_PROFILE_LEFT: "elf_female_base_profile_left",
  ELF_FEMALE_BASE_PROFILE_RIGHT: "elf_female_base_profile_right",
  ELF_FEMALE_BASE_BACK: "elf_female_base_back",
};

export const PLAYER = {
  BASE_SPEED: 200,
  SPRINT_SPEED: 320,
  SCALE: 0.1,
  DAMAGE_TAKEN: 10,
  HIT_COOLDOWN_MS: 400,
  RESPAWN_DELAY_MS: 800,
  RESPAWN_INVULN_MS: 1200,
  INVULN_FLICKER_MS: 100,
  KNOCKBACK_FORCE: 260,
  HIT_STUN_MS: 180,
  HITSTOP_MS: 60,
  SHAKE_DURATION_MS: 120,
  SHAKE_INTENSITY: 0.01,
  ATTACK_COOLDOWN_MS: 350,
  ATTACK_ACTIVE_MS: 90,
  ATTACK_FEEDBACK_MS: 120,
};

export const GAME = {
  WIDTH: 1280,
  HEIGHT: 720,
  WORLD_WIDTH: 2000,
  WORLD_HEIGHT: 2000,
};

export const ENEMY = {
  SCALE: 0.08,
  SPEED: 140,
  STOP_DISTANCE: 40,
  ATTACK_COOLDOWN_MS: 900,
  XP_REWARD: 25,
};
